DeckOfCardsApiLab/Models/DeckApi.cs
namespace DeckOfCardsApiLab.Models
{
    public class DeckApi
    {
        public bool success { get; set; }
        public string deck_id { get; set; }
        public int remaining { get; set; }
        public bool shuffled { get; set; }
    }
}

DeckOfCardsApiLab/Models/DeckCardsApi.cs
namespace DeckOfCardsApiLab.Models
{
    public class DeckCardsApi
    {
        public string code { get; set; }
        public string image { get; set; }
        public string value { get; set; }
        public string suit { get; set; }
    }
}

DeckOfCardsApiLab/Models/DeckDrawApi.cs
namespace DeckOfCardsApiLab.Models
{
    public class DeckDrawApi
    {
        public bool success { get; set; }
        public string deck_id { get; set; }
        public List<DeckCardsApi> cards { get; set; }
        public int remaining { get; set; }
    }
}

DeckOfCardsApiLab/Models/ErrorViewModel.cs
namespace DeckOfCardsApiLab.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeckOfCardsApiLab/Controllers/DeckController.cs
using Microsoft.AspNetCore.Mvc;
using DeckOfCardsApiLab.Models;
using Flurl.Http;

namespace DeckOfCardsApiLab.Controllers
{
    public class DeckController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Draw5(DeckDrawApi transfer)
        {
            string apiUri = $"https://deckofcardsapi.com/api/deck/{transfer.deck_id}/draw/?count=5";
            var apiTask = apiUri.GetJsonAsync<DeckDrawApi>();
            apiTask.Wait();
            DeckDrawApi draw = apiTask.Result;
            return View(draw);
        }
        public ActionResult GenerateDeck() 
        {
            string apiUri = "https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1";
            var apiTask = apiUri.GetJsonAsync<DeckApi>();
            apiTask.Wait();
            DeckApi result = apiTask.Result;
            DeckDrawApi transfer = new DeckDrawApi();
            transfer.deck_id = result.deck_id;
            return RedirectToAction("Draw5", transfer);
        }
        public ActionResult Reshuffle(DeckDrawApi transfer)
        {
            string apiUri = $"https://deckofcardsapi.com/api/deck/{transfer.deck_id}/shuffle/";
            var apiTask = apiUri.GetJsonAsync<DeckDrawApi>();
            apiTask.Wait();
            DeckDrawApi newDeck = apiTask.Result;
            return RedirectToAction("Draw5", newDeck);
        }
    }
}

DeckOfCardsApiLab/Controllers/HomeController.cs
using DeckOfCardsApiLab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DeckOfCardsApiLab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeckOfCardsApiLab/Views/Deck/Draw5.cshtml
@model DeckOfCardsApiLab.Models.DeckDrawApi

@{
    ViewData["Title"] = "Draw5";
}

<h1>Drawn Cards</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.cards[0].image)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.cards[0].value)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.cards[0].suit)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var card in Model.cards)
        {
            <tr>
                <td>
                    <a href="@card.image" target="_blank"><img src="@card.image" /></a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => card.value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => card.suit)
                </td>
            </tr>
        }
    </tbody>
</table>
<p>@Html.DisplayFor(model => model.remaining) cards remaining in deck</p>
<td>
    @Html.ActionLink("Draw 5 More", "Draw5", Model)
</td>
<br />
<td>
    <a asp-area="" asp-controller="Home" asp-action="Index">Return to Home</a>
</td>
<br />
<td>
    @Html.ActionLink("Reshuffle the Deck and Draw 5 More", "Reshuffle", Model)
</td>

DeckOfCardsApiLab/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a asp-area="" asp-controller="Deck" asp-action="GenerateDeck">Click Here To Draw 5 Cards from a New Deck</a></p>
</div>

DeckOfCardsApiLab/Views/Home/Test.cshtml
@model DeckOfCardsApiLab.Models.DeckApi

@{
    ViewData["Title"] = "Test";
}

<h1>Test</h1>

<h4>DeckApi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Test">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="success" /> @Html.DisplayNameFor(model => model.success)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="deck_id" class="control-label"></label>
                <input asp-for="deck_id" class="form-control" />
                <span asp-validation-for="deck_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="remaining" class="control-label"></label>
                <input asp-for="remaining" class="form-control" />
                <span asp-validation-for="remaining" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="shuffled" /> @Html.DisplayNameFor(model => model.shuffled)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeckOfCardsApiLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeckOfCardsApiLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeckOfCardsApiLab.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeckOfCardsApiLab</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeckOfCardsApiLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>